apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: {{team}}
  name: familie-dokgen
  namespace: default
spec:
  image: docker.pkg.github.com/navikt/familie-dokgen-java/familie-dokgen:{{version}}
  port: 8080
  team: {{team}}
  liveness:
    path: /actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  leaderElection: false
  istio:
    enabled: false
  resources:
    limits:
      cpu: 500m # app will have its cpu usage throttled if exceeding this limit
      memory: 512Mi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://familie-dokgen.nais.preprod.local/"
  logformat: accesslog
  logtransform: dns_loglevel
  webproxy: false
  vault:
    enabled: false
  env:
    - name: APP_VERSION
      value: {{version}}
    - name: APP_TEAM
      value: {{team}}
