path.content.root: ./content/
write.access: false

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/actuator"
  observations:
    http:
      client:
        requests:
          name: http_client_requests, http_client_requests_seconds, http_client_requests_seconds_max, http_client_requests_seconds_sum
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  main:
    banner-mode: 'off'
  hateoas:
    use-hal-as-default-json-media-type: false
  lifecycle:
    timeout-per-shutdown-phase: 5s

logging:
  config: "classpath:logback-spring.xml"
springdoc:
  swagger-ui:
    path: /swagger
  enable-hateoas: false
