path.content.root: ./content/
write.access: false
allow-encoded-slash: ${ALLOW_ENCODED_SLASH:false}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/actuator"
  observations:
    http:
      client:
        requests:
          name: http_client_requests, http_client_requests_seconds, http_client_requests_seconds_max, http_client_requests_seconds_sum
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  main:
    banner-mode: 'off'

logging:
  config: "classpath:logback-spring.xml"
springdoc:
  swagger-ui:
    path: /swagger
