allow-encoded-slash: ${ALLOW_ENCODED_SLASH:false}

path:
  content:
    root: ./content/

write:
  access: false

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/actuator"
  observations:
    http:
      client:
        requests:
          name: http_client_requests, http_client_requests_seconds, http_client_requests_seconds_max, http_client_requests_seconds_sum
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: "classpath:logback-spring.xml"
springdoc:
  swagger-ui:
    path: /swagger
