path.content.root: ./content/
write.access: false
allow-encoded-slash: ${ALLOW_ENCODED_SLASH:false}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/actuator"
  metrics.export.prometheus.enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

logging:
  config: "classpath:logback-spring.xml"