name: Build-Publish

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '22 22 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}/dokgen:${{ github.sha }}, ghcr.io/${{ github.repository }}/dokgen:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
