name: Build-Publish

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '22 22 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
        run: mvn -B --no-transfer-progress package verify --settings .m2/maven-settings.xml --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: k9saksbehandling # Brukes kun for innlogging
          push_image: ${{ github.ref_name == 'master' }}
          tag: ghcr.io/${{ github.repository }}/dokgen:${{ github.sha }}, ghcr.io/${{ github.repository }}/dokgen:latest
          platforms: linux/amd64,linux/arm64
